# Generated by Django 3.1.7 on 2021-07-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbvApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lastName',
            field=models.TextField(max_length=2000),
        ),
    ]
