# Generated by Django 3.2.4 on 2021-07-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbvApp', '0002_auto_20210715_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Topic',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
